In [1]:
import tensorflow as tf
import numpy as np

x_train = np.array([[1., 1.],
                   [1., 2.],
                   [2., 1.],
                   [3., 2.],
                   [3., 3.],
                   [2., 3.]],
                   dtype=np.float32)

y_train = np.array([[0.],
                   [0.],
                   [0.],
                   [1.],
                   [1.],
                   [1.]],
                   dtype=np.float32)



tf.random.set_seed(12345)
W = tf.Variable(tf.random.normal([2, 1], mean=0.0))
b = tf.Variable(tf.random.normal([1], mean=0.0))

print('weights: \n', W.numpy(), '\n\nbias: \n', b.numpy())

weights: 
 [[0.2737803 ]
 [0.08836086]] 

bias: 
 [0.21987937]


In [2]:
learning_rate = 0.01


def predict(X):
    z = tf.matmul(X, W) + b
    hypothesis = 1 / (1 + tf.exp(-z))
    return hypothesis

for i in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = predict(x_train)
        cost = tf.reduce_mean(-tf.reduce_sum(y_train*tf.math.log(hypothesis) + (1-y_train)*tf.math.log(1-hypothesis)))
        W_grad, b_grad = tape.gradient(cost, [W, b])

        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)

    if i % 400 == 0:
        print("{} \n weights: \n{} \n bias: \n{} \n cost: {}\n".format(i, W.numpy(), b.numpy(), cost.numpy()))


0 
 weights: 
[[0.2652075 ]
 [0.08053297]] 
 bias: 
[0.20687035] 
 cost: 4.122779846191406

400 
 weights: 
[[0.712996 ]
 [0.6827528]] 
 bias: 
[-2.3853571] 
 cost: 2.1599490642547607

800 
 weights: 
[[1.0833972]
 [1.0773938]] 
 bias: 
[-3.974235] 
 cost: 1.445218563079834

1200 
 weights: 
[[1.3559325]
 [1.3544557]] 
 bias: 
[-5.102907] 
 cost: 1.0861058235168457

1600 
 weights: 
[[1.5694492]
 [1.5690154]] 
 bias: 
[-5.97691] 
 cost: 0.8711534142494202

2000 
 weights: 
[[1.7447244]
 [1.744578 ]] 
 bias: 
[-6.690599] 
 cost: 0.7279360294342041



In [3]:
hypo = predict(x_train)
print("hypothesis: \n", hypo.numpy())
print("result: \n", tf.cast(hypo > 0.5, dtype=tf.float32).numpy())
def acc(hypo, label):
    predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, label), dtype=tf.float32))
    return accuracy

accuracy = acc(predict(x_train), y_train).numpy()
print("accuracy: %s" % accuracy)


hypothesis: 
 [[0.03911696]
 [0.18896975]
 [0.18899219]
 [0.884191  ]
 [0.9776277 ]
 [0.88417596]]
result: 
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
accuracy: 1.0
